### PR TITLE
Add bors bot support

### PR DESCRIPTION
**Pull request by tgrospic**

### CODE REVIEW

**Comment by tgrospic** [comment]
bors ping

**Comment by tgrospic** [comment]
bors ping

**Comment by tgrospic** [comment]
bors ping

**Comment by tgrospic** [comment]
bors ztry

**Comment by tgrospic** [comment]
bors try

**Comment by tgrospic** [comment]
bors ping

**Comment by tgrospic** [comment]
bors try

**Comment by tgrospic** [comment]
bors try

**Comment by tgrospic** [comment]
bors try

**Comment by tgrospic** [comment]
bors merge

**Comment by tgrospic** [comment]
bors try

**Review by nzpr — APPROVED** [review]
LGTM

**Comment by tgrospic** [comment]
bors merge

**Pull request merged**
